[manifest]
id = "ProxyMM_CustomItem"
version = "0.0.2"
display_name = "CustomItem"
description =  """
A library for spawning and giving custom items.
"""
short_description = "A library for spawning and giving custom items."
authors = [ "ProxySaw" ]
game_id = "mm"
minimum_recomp_version = "1.2.0"
dependencies = [
    "ProxyMM_ObjDepLoader:0.0.2"
]
native_libraries = []

[inputs]
elf_path = "../../build/packages/CustomItem/mod.elf"
mod_filename = "ProxyMM_CustomItem"
func_reference_syms_file = "../../Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "../../Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "../../Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]
additional_files = [ "thumb.png" ]
