[manifest]
id = "ProxyMM_3DItems"
version = "0.0.1"
display_name = "3DItems"
description =  """
Replaces 2d Sprites with their 3D counterparts throughout the game.
"""
short_description = "Replaces 2d Sprites with their 3D counterparts throughout the game."
authors = [ "ProxySaw" ]
game_id = "mm"
minimum_recomp_version = "1.2.0"
dependencies = [
    "ProxyMM_ObjDepLoader:0.0.3"
]
native_libraries = []

[inputs]
elf_path = "../../build/packages/3DItems/mod.elf"
mod_filename = "ProxyMM_3DItems"
func_reference_syms_file = "../../Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "../../Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "../../Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml", "../../custom_syms.toml" ]
additional_files = [ "thumb.png" ]
