[manifest]
id = "ProxyMM_ObjDepLoader"
version = "0.0.2"
display_name = "ObjDepLoader"
description =  """
A simple workaround for object dependency
"""
short_description = "A simple workaround for object dependency"
authors = [ "ProxySaw" ]
game_id = "mm"
minimum_recomp_version = "1.2.0"
dependencies = []
native_libraries = []

[inputs]
elf_path = "../../build/packages/ObjDepLoader/mod.elf"
mod_filename = "ProxyMM_ObjDepLoader"
func_reference_syms_file = "../../Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "../../Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "../../Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]
additional_files = [ "thumb.png" ]
