[manifest]
id = "ProxyMM_Notifications"
version = "0.0.1"
display_name = "Notifications"
description =  """
A simple text notification system
"""
short_description = "A simple text notification system"
authors = [ "ProxySaw" ]
game_id = "mm"
minimum_recomp_version = "1.2.0"
dependencies = []
native_libraries = []

[inputs]
elf_path = "../../build/packages/Notifications/mod.elf"
mod_filename = "ProxyMM_Notifications"
func_reference_syms_file = "../../Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "../../Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "../../Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]
additional_files = [ "thumb.png" ]
