DEFINE_SCENE(SCENE_20SICHITAI2,       SOUTHERN_SWAMP_CLEARED,        31, "Southern Swamp (Clear)")
DEFINE_SCENE(SCENE_KAKUSIANA,         GROTTOS,                       98, "Lone Peak Shrine & Grottos")
DEFINE_SCENE(SCENE_SPOT00,            CUTSCENE,                     100, "Cutscene Scene")
DEFINE_SCENE(SCENE_WITCH_SHOP,        MAGIC_HAGS_POTION_SHOP,        33, "Magic Hags' Potion Shop")
DEFINE_SCENE(SCENE_LAST_BS,           MAJORAS_LAIR,                  96, "Majora's Lair")
DEFINE_SCENE(SCENE_HAKASHITA,         BENEATH_THE_GRAVERYARD,        60, "Beneath the Graveyard")
DEFINE_SCENE(SCENE_AYASHIISHOP,       CURIOSITY_SHOP,                11, "Curiosity Shop")
DEFINE_SCENE(SCENE_OMOYA,             RANCH_HOUSE,                   25, "Mama's House & Barn")
DEFINE_SCENE(SCENE_BOWLING,           HONEY_AND_DARLINGS_SHOP,       15, "Honey & Darling's Shop")
DEFINE_SCENE(SCENE_SONCHONOIE,        MAYORS_RESIDENCE,               5, "The Mayor's Residence")
DEFINE_SCENE(SCENE_IKANA,             IKANA_CANYON,                  62, "Ikana Canyon")
DEFINE_SCENE(SCENE_KAIZOKU,           PIRATES_FORTRESS,              87, "Pirates' Fortress")
DEFINE_SCENE(SCENE_MILK_BAR,          MILK_BAR,                      10, "Milk Bar")
DEFINE_SCENE(SCENE_INISIE_N,          STONE_TOWER_TEMPLE,            72, "Stone Tower Temple")
DEFINE_SCENE(SCENE_TAKARAYA,          TREASURE_CHEST_SHOP,           14, "Treasure Chest Shop")
DEFINE_SCENE(SCENE_INISIE_R,          STONE_TOWER_TEMPLE_INVERTED,   73, "Inverted Stone Tower Temple")
DEFINE_SCENE(SCENE_OKUJOU,            CLOCK_TOWER_ROOFTOP,           20, "Clock Tower Rooftop")
DEFINE_SCENE(SCENE_OPENINGDAN,        OPENING_DUNGEON,               18, "Before Clock Town")
DEFINE_SCENE(SCENE_MITURIN,           WOODFALL_TEMPLE,               40, "Woodfall Temple")
DEFINE_SCENE(SCENE_13HUBUKINOMITI,    PATH_TO_MOUNTAIN_VILLAGE,      42, "Path to Mountain Village")
DEFINE_SCENE(SCENE_CASTLE,            IKANA_CASTLE,                  68, "Ancient Castle of Ikana")
DEFINE_SCENE(SCENE_DEKUTES,           DEKU_SCRUB_PLAYGROUND,         99, "Deku Scrub Playground")
DEFINE_SCENE(SCENE_MITURIN_BS,        ODOLWAS_LAIR,                  41, "Odolwa's Lair")
DEFINE_SCENE(SCENE_SYATEKI_MIZU,      TOWN_SHOOTING_GALLERY,         16, "Town Shooting Gallery")
DEFINE_SCENE(SCENE_HAKUGIN,           SNOWHEAD_TEMPLE,               56, "Snowhead Temple")
DEFINE_SCENE(SCENE_ROMANYMAE,         MILK_ROAD,                     22, "Milk Road")
DEFINE_SCENE(SCENE_PIRATE,            PIRATES_FORTRESS_INTERIOR,     88, "Pirates' Fortress Interior")
DEFINE_SCENE(SCENE_SYATEKI_MORI,      SWAMP_SHOOTING_GALLERY,        29, "Swamp Shooting Gallery")
DEFINE_SCENE(SCENE_SINKAI,            PINNACLE_ROCK,                 79, "Pinnacle Rock")
DEFINE_SCENE(SCENE_YOUSEI_IZUMI,      FAIRY_FOUNTAIN,                97, "Fairy's Fountain")
DEFINE_SCENE(SCENE_KINSTA1,           SWAMP_SPIDER_HOUSE,            34, "Swamp Spider House")
DEFINE_SCENE(SCENE_KINDAN2,           OCEANSIDE_SPIDER_HOUSE,        85, "Oceanside Spider House")
DEFINE_SCENE(SCENE_TENMON_DAI,        ASTRAL_OBSERVATORY,             6, "Astral Observatory")
DEFINE_SCENE(SCENE_LAST_DEKU,         MOON_DEKU_TRIAL,               92, "Moon Deku Trial")
DEFINE_SCENE(SCENE_22DEKUCITY,        DEKU_PALACE,                   35, "Deku Palace")
DEFINE_SCENE(SCENE_KAJIYA,            MOUNTAIN_SMITHY,               45, "Mountain Smithy")
DEFINE_SCENE(SCENE_00KEIKOKU,         TERMINA_FIELD,                 21, "Termina Field")
DEFINE_SCENE(SCENE_POSTHOUSE,         POST_OFFICE,                    8, "Post Office")
DEFINE_SCENE(SCENE_LABO,              MARINE_RESEARCH_LAB,           78, "Marine Research Lab")
DEFINE_SCENE(SCENE_DANPEI2TEST,       DAMPES_HOUSE,                  61, "Beneath Graveyard and Dampe's House")
DEFINE_SCENE(SCENE_16GORON_HOUSE,     GORON_SHRINE,                  52, "Goron Shrine")
DEFINE_SCENE(SCENE_33ZORACITY,        ZORA_HALL,                     80, "Zora Hall")
DEFINE_SCENE(SCENE_8ITEMSHOP,         TRADING_POST,                  13, "Trading Post")
DEFINE_SCENE(SCENE_F01,               ROMANI_RANCH,                  24, "Romani Ranch")
DEFINE_SCENE(SCENE_INISIE_BS,         TWINMOLDS_LAIR,                74, "Twinmold's Lair")
DEFINE_SCENE(SCENE_30GYOSON,          GREAT_BAY_COAST,               76, "Great Bay Coast")
DEFINE_SCENE(SCENE_31MISAKI,          ZORA_CAPE,                     82, "Zora Cape")
DEFINE_SCENE(SCENE_TAKARAKUJI,        LOTTERY_SHOP,                  17, "Lottery Shop")
DEFINE_SCENE(SCENE_TORIDE,            PIRATES_FORTRESS_EXTERIOR,     86, "Pirates' Fortress Moat")
DEFINE_SCENE(SCENE_FISHERMAN,         FISHERMANS_HUT,                83, "Fisherman's Hut")
DEFINE_SCENE(SCENE_GORONSHOP,         GORON_SHOP,                    53, "Goron Shop")
DEFINE_SCENE(SCENE_DEKU_KING,         DEKU_KINGS_CHAMBER,            37, "Deku King's Chamber")
DEFINE_SCENE(SCENE_LAST_GORON,        MOON_GORON_TRIAL,              93, "Moon Goron Trial")
DEFINE_SCENE(SCENE_24KEMONOMITI,      ROAD_TO_SOUTHERN_SWAMP,        28, "Road to Southern Swamp")
DEFINE_SCENE(SCENE_F01_B,             DOGGY_RACETRACK,               27, "Doggy Racetrack")
DEFINE_SCENE(SCENE_F01C,              CUCCO_SHACK,                   26, "Cucco Shack")
DEFINE_SCENE(SCENE_BOTI,              IKANA_GRAVEYARD,               59, "Ikana Graveyard")
DEFINE_SCENE(SCENE_HAKUGIN_BS,        GOHTS_LAIR,                    57, "Goht's Lair")
DEFINE_SCENE(SCENE_20SICHITAI,        SOUTHERN_SWAMP_POISONED,       30, "Southern Swamp (poison)")
DEFINE_SCENE(SCENE_21MITURINMAE,      WOODFALL,                      39, "Woodfall")
DEFINE_SCENE(SCENE_LAST_ZORA,         MOON_ZORA_TRIAL,               94, "Moon Zora Trial")
DEFINE_SCENE(SCENE_11GORONNOSATO2,    GORON_VILLAGE_SPRING,          51, "Goron Village (spring)")
DEFINE_SCENE(SCENE_SEA,               GREAT_BAY_TEMPLE,              89, "Great Bay Temple")
DEFINE_SCENE(SCENE_35TAKI,            WATERFALL_RAPIDS,              84, "Waterfall Rapids")
DEFINE_SCENE(SCENE_REDEAD,            BENEATH_THE_WELL,              65, "Beneath the Well")
DEFINE_SCENE(SCENE_BANDROOM,          ZORA_HALL_ROOMS,               81, "Zora Hall Rooms")
DEFINE_SCENE(SCENE_11GORONNOSATO,     GORON_VILLAGE_WINTER,          50, "Goron Village (winter)")
DEFINE_SCENE(SCENE_GORON_HAKA,        GORON_GRAVERYARD,              46, "Goron Graveyard")
DEFINE_SCENE(SCENE_SECOM,             SAKONS_HIDEOUT,                63, "Sakon's Hideout")
DEFINE_SCENE(SCENE_10YUKIYAMANOMURA,  MOUNTAIN_VILLAGE_WINTER,       43, "Mountain Village (winter)")
DEFINE_SCENE(SCENE_TOUGITES,          GHOST_HUT,                     66, "Ghost Hut")
DEFINE_SCENE(SCENE_DANPEI,            DEKU_SHRINE,                   36, "Deku Shrine")
DEFINE_SCENE(SCENE_IKANAMAE,          ROAD_TO_IKANA,                 58, "Road to Ikana")
DEFINE_SCENE(SCENE_DOUJOU,            SWORDMANS_SCHOOL,               7, "Swordsman's School")
DEFINE_SCENE(SCENE_MUSICHOUSE,        MUSIC_BOX_HOUSE,               64, "Music Box House")
DEFINE_SCENE(SCENE_IKNINSIDE,         IGOS_DU_IKANAS_LAIR,           69, "Igos du Ikana's Lair")
DEFINE_SCENE(SCENE_MAP_SHOP,          TOURIST_INFORMATION,           32, "Tourist Information")
DEFINE_SCENE(SCENE_F40,               STONE_TOWER,                   70, "Stone Tower")
DEFINE_SCENE(SCENE_F41,               STONE_TOWER_INVERTED,          71, "Inverted Stone Tower")
DEFINE_SCENE(SCENE_10YUKIYAMANOMURA2, MOUNTAIN_VILLAGE_SPRING,       44, "Mountain Village (spring)")
DEFINE_SCENE(SCENE_14YUKIDAMANOMITI,  PATH_TO_SNOWHEAD,              54, "Path to Snowhead")
DEFINE_SCENE(SCENE_12HAKUGINMAE,      SNOWHEAD,                      55, "Snowhead")
DEFINE_SCENE(SCENE_17SETUGEN,         PATH_TO_GORON_VILLAGE_WINTER,  47, "Path to Goron Village (winter)")
DEFINE_SCENE(SCENE_17SETUGEN2,        PATH_TO_GORON_VILLAGE_SPRING,  48, "Path to Goron Village (spring)")
DEFINE_SCENE(SCENE_SEA_BS,            GYORGS_LAIR,                   90, "Gyorg's Lair")
DEFINE_SCENE(SCENE_RANDOM,            SECRET_SHRINE,                 67, "Secret Shrine")
DEFINE_SCENE(SCENE_YADOYA,            STOCK_POT_INN,                  9, "Stock Pot Inn")
DEFINE_SCENE(SCENE_KONPEKI_ENT,       GREAT_BAY_CUTSCENE,            77, "Great Bay Cutscene")
DEFINE_SCENE(SCENE_INSIDETOWER,       CLOCK_TOWER_INTERIOR,          19, "Clock Tower Interior")
DEFINE_SCENE(SCENE_26SARUNOMORI,      WOODS_OF_MYSTERY,              38, "Woods of Mystery")
DEFINE_SCENE(SCENE_LOST_WOODS,        LOST_WOODS,                   101, "Lost Woods (Intro)")
DEFINE_SCENE(SCENE_LAST_LINK,         MOON_LINK_TRIAL,               95, "Moon Link Trial")
DEFINE_SCENE(SCENE_SOUGEN,            THE_MOON,                      91, "The Moon")
DEFINE_SCENE(SCENE_BOMYA,             BOMB_SHOP,                     12, "Bomb Shop")
DEFINE_SCENE(SCENE_KYOJINNOMA,        GIANTS_CHAMBER,                75, "Giants' Chamber")
DEFINE_SCENE(SCENE_KOEPONARACE,       GORMAN_TRACK,                  23, "Gorman Track")
DEFINE_SCENE(SCENE_GORONRACE,         GORON_RACETRACK,               49, "Goron Racetrack")
DEFINE_SCENE(SCENE_TOWN,              EAST_CLOCK_TOWN,                1, "East Clock Town")
DEFINE_SCENE(SCENE_ICHIBA,            WEST_CLOCK_TOWN,                2, "West Clock Town")
DEFINE_SCENE(SCENE_BACKTOWN,          NORTH_CLOCK_TOWN,               3, "North Clock Town")
DEFINE_SCENE(SCENE_CLOCKTOWER,        SOUTH_CLOCK_TOWN,               0, "South Clock Town")
DEFINE_SCENE(SCENE_ALLEY,             LAUNDRY_POOL,                   4, "Laundry Pool")
