[manifest]
id = "ProxyMM_DevTools"
version = "0.0.7"
display_name = "DevTools"
description =  """
A collection of developer tools to make my life easier, some ported from 2Ship some created for Recomp.

All features are off by default, and need to be enabled in the Configuration menu.

Features:
- Hold L to levitate
- Inventory Editor - Press L on the pause menu to enable editing of the inventory, then press A to grant/remove an item
- Map Select - L + R + Z Brings you to a map select screen, allowing you to warp to various scenes/entrances/cutscenes
- Debug Save - New files created with 100% of the inventory filled
- No Clip - Ported from OoT Debug mode, Hold L and press D-pad right to activate
- Disable HUD
- Custom Screen Scale & Letterboxing
"""
short_description = "A collection of developer tools"
authors = [ "ProxySaw" ]
game_id = "mm"
minimum_recomp_version = "1.2.0"
dependencies = [
    "ProxyMM_KV:0.0.3"
]
native_libraries = []

[inputs]
elf_path = "../../build/packages/DevTools/mod.elf"
mod_filename = "ProxyMM_DevTools"
func_reference_syms_file = "../../Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "../../Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "../../Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml", "../../custom_syms.toml" ]
additional_files = [ "thumb.png" ]

[[manifest.config_options]]
id = "l_to_levitate"
name = "Hold L to levitate"
description = ""
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "inventory_editor"
name = "Inventory Editor"
description = "Press L on the pause menu to enable editing of the inventory, then press A to grant/remove an item"
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "map_select"
name = "Map Select"
description = "L + R + Z Brings you to a map select screen, allowing you to warp to various scenes/entrances/cutscenes"
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "debug_save"
name = "Debug Save"
description = "New files created with 100% of the inventory filled"
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "no_clip"
name = "No Clip"
description = "Ported from OoT Debug mode, Hold L and press D-pad right to activate"
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "disable_hud"
name = "Disable Hud"
description = "Hides the HUD and Message interfaces. You may need to disable to continue messages."
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "screen_scale"
name = "Screen Scale"
description = "100% is no change"
type = "Number"
min = 0
max = 100
step = 1
precision = 1
percent = true
default = 100

[[manifest.config_options]]
id = "letterbox_size"
name = "Letterbox Size"
description = "-1 is no override (vanilla), 0 will prevent all letterboxing"
type = "Number"
min = -1
max = 120
step = 1
precision = 1
percent = false
default = -1
