[manifest]
id = "ProxyMM_SkipIt"
version = "0.0.6"
display_name = "SkipIt"
description =  """
Various cutscene skip options

Features:
- Skip One Point Cutscenes
- Skip Entrance Cutscenes
- Skip Boss Introductions
- Skip Intro or First Cycle
- Skip Song Playback
- Skip To File Select
- Skip Mask Transformation
- More planned
"""
short_description = "Various cutscene skip options"
authors = [ "ProxySaw" ]
game_id = "mm"
minimum_recomp_version = "1.2.0"
dependencies = []
native_libraries = []

[inputs]
elf_path = "../../build/packages/SkipIt/mod.elf"
mod_filename = "ProxyMM_SkipIt"
func_reference_syms_file = "../../Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "../../Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "../../Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml", "../../custom_syms.toml" ]
additional_files = [ "thumb.png" ]

[[manifest.config_options]]
id = "skip_one_point_cutscenes"
name = "Skip One Point Cutscenes"
description = "Prevents you from being locked into place focusing on things like chests spawning or switches being flipped."
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "skip_entrance_cutscenes"
name = "Skip Entrance Cutscenes"
description = "Skips any entrance related cutscenes when entering an area for the first time."
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "skip_boss_introductions"
name = "Skip Boss Introductions"
description = "Skips boss introduction cutscenes, which play the first time you encounter a boss."
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "skip_intro"
name = "Skip Intro"
description = "Skips either the intro sequence, or the entire first cycle"
type = "Enum"
options = [ "Off", "Skip Intro", "Skip First Cycle" ]
default = "Off"

[[manifest.config_options]]
id = "skip_song_playback"
name = "Skip Song Playback"
description = "Skips replaying the song after you play it on an instrument"
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "skip_to_file_select"
name = "Skip To File Select"
description = "Skips to File select screen when booting"
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "skip_transformation"
name = "Skip Mask Transformation"
description = "Skip Mask Transformation animation"
type = "Enum"
options = [ "Off", "On" ]
default = "Off"
