#ifndef OBJECT_BAL_H
#define OBJECT_BAL_H

typedef enum TingleLimb {
    /* 0x00 */ TINGLE_LIMB_NONE,
    /* 0x01 */ TINGLE_LIMB_ROOT,
    /* 0x02 */ TINGLE_LIMB_PELVIS,
    /* 0x03 */ TINGLE_LIMB_UPPER_BODY_ROOT,
    /* 0x04 */ TINGLE_LIMB_UPPER_BODY_WRAPPER,
    /* 0x05 */ TINGLE_LIMB_BALLOON_ROOT,
    /* 0x06 */ TINGLE_LIMB_BALLOON,
    /* 0x07 */ TINGLE_LIMB_RIGHT_ARM_ROOT,
    /* 0x08 */ TINGLE_LIMB_RIGHT_ARM_WRAPPER,
    /* 0x09 */ TINGLE_LIMB_RIGHT_UPPER_ARM,
    /* 0x0A */ TINGLE_LIMB_RIGHT_FOREARM,
    /* 0x0B */ TINGLE_LIMB_RIGHT_HAND_ROOT,
    /* 0x0C */ TINGLE_LIMB_RIGHT_HAND,
    /* 0x0D */ TINGLE_LIMB_HELD_PEN,
    /* 0x0E */ TINGLE_LIMB_LEFT_ARM_ROOT,
    /* 0x0F */ TINGLE_LIMB_LEFT_ARM_WRAPPER,
    /* 0x10 */ TINGLE_LIMB_LEFT_UPPER_ARM,
    /* 0x11 */ TINGLE_LIMB_LEFT_FOREARM,
    /* 0x12 */ TINGLE_LIMB_LEFT_HAND_ROOT,
    /* 0x13 */ TINGLE_LIMB_LEFT_HAND,
    /* 0x14 */ TINGLE_LIMB_HELD_MAP,
    /* 0x15 */ TINGLE_LIMB_TORSO,
    /* 0x16 */ TINGLE_LIMB_HEAD,
    /* 0x17 */ TINGLE_LIMB_RIGHT_LEG_ROOT,
    /* 0x18 */ TINGLE_LIMB_RIGHT_THIGH,
    /* 0x19 */ TINGLE_LIMB_RIGHT_LOWER_LEG_ROOT,
    /* 0x1A */ TINGLE_LIMB_RIGHT_SHIN,
    /* 0x1B */ TINGLE_LIMB_RIGHT_FOOT,
    /* 0x1C */ TINGLE_LIMB_LEFT_LEG_ROOT,
    /* 0x1D */ TINGLE_LIMB_LEFT_THIGH,
    /* 0x1E */ TINGLE_LIMB_LEFT_LOWER_LEG_ROOT,
    /* 0x1F */ TINGLE_LIMB_LEFT_SHIN,
    /* 0x20 */ TINGLE_LIMB_LEFT_FOOT,
    /* 0x21 */ TINGLE_LIMB_MAX
} TingleLimb;

#endif // OBJECT_BAL_H
